FROM eclipse-temurin:17 AS get-dependencies
WORKDIR /backend
COPY Backend/demo/pom.xml .
COPY Backend/demo/mvnw .
COPY Backend/demo/.mvn ./.mvn 
RUN ./mvnw dependency:go-offline -DskipTests

FROM eclipse-temurin:17
WORKDIR /backend
COPY --from=get-dependencies /root/.m2 /root/.m2
COPY Backend/demo/ .
RUN chmod +x ./mvnw
EXPOSE 8080
CMD [ "./mvnw", "spring-boot:run"]