// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/search/:keyword": {
    params: {
      "keyword": string;
    };
  };
  "/job/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/profile": {
    params: {};
  };
  "/company/cv/list": {
    params: {};
  };
  "/company/cv/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/company/detail": {
    params: {};
  };
  "/company/job/create": {
    params: {};
  };
  "/company/job/list": {
    params: {};
  };
  "/company/login": {
    params: {};
  };
  "/company/register": {
    params: {};
  };
  "/user/cv/list": {
    params: {};
  };
  "/user/login": {
    params: {};
  };
  "/user/register": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
  "/dashboard/list": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/search/:keyword" | "/job/detail/:id" | "/dashboard/profile" | "/company/cv/list" | "/company/cv/detail/:id" | "/company/detail" | "/company/job/create" | "/company/job/list" | "/company/login" | "/company/register" | "/user/cv/list" | "/user/login" | "/user/register" | "/user/profile" | "/dashboard/list" | "/*";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/SearchHome.tsx": {
    id: "pages/SearchHome";
    page: "/search";
  };
  "./pages/search/page.tsx": {
    id: "pages/search/page";
    page: "/search/:keyword";
  };
  "./pages/job/detail/page.tsx": {
    id: "pages/job/detail/page";
    page: "/job/detail/:id";
  };
  "./pages/dashboard/profile/page.tsx": {
    id: "pages/dashboard/profile/page";
    page: "/dashboard/profile";
  };
  "./pages/company/cv/list/page.tsx": {
    id: "pages/company/cv/list/page";
    page: "/company/cv/list";
  };
  "./pages/company/cv/detail/page.tsx": {
    id: "pages/company/cv/detail/page";
    page: "/company/cv/detail/:id";
  };
  "./pages/company/detail/page.tsx": {
    id: "pages/company/detail/page";
    page: "/company/detail";
  };
  "./pages/company/job/create/page.tsx": {
    id: "pages/company/job/create/page";
    page: "/company/job/create";
  };
  "./pages/company/job/list/page.tsx": {
    id: "pages/company/job/list/page";
    page: "/company/job/list";
  };
  "./pages/company/login/page.tsx": {
    id: "pages/company/login/page";
    page: "/company/login";
  };
  "./pages/company/register/page.tsx": {
    id: "pages/company/register/page";
    page: "/company/register";
  };
  "./pages/user/cv/list/page.tsx": {
    id: "pages/user/cv/list/page";
    page: "/user/cv/list";
  };
  "./pages/user/login/page.tsx": {
    id: "pages/user/login/page";
    page: "/user/login";
  };
  "./pages/user/register/page.tsx": {
    id: "pages/user/register/page";
    page: "/user/register";
  };
  "./pages/user/profile/page.tsx": {
    id: "pages/user/profile/page";
    page: "/user/profile";
  };
  "./pages/dashboard/list/page.tsx": {
    id: "pages/dashboard/list/page";
    page: "/dashboard/list";
  };
  "./pages/catchall.tsx": {
    id: "pages/catchall";
    page: "/*";
  };
};