// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/search/:keyword": {
    params: {
      "keyword": string;
    };
  };
  "/job/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/company/profile": {
    params: {};
  };
  "/company/cv/list": {
    params: {};
  };
  "/company/cv/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/company/job/list": {
    params: {};
  };
  "/company/job/create": {
    params: {};
  };
  "/company/list": {
    params: {};
  };
  "/company/detail/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/search/:keyword" | "/job/detail/:id" | "/company/profile" | "/company/cv/list" | "/company/cv/detail/:id" | "/company/job/list" | "/company/job/create" | "/company/list" | "/company/detail/:id" | "/*";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/SearchHome.tsx": {
    id: "pages/SearchHome";
    page: "/search";
  };
  "./pages/search/page.tsx": {
    id: "pages/search/page";
    page: "/search/:keyword";
  };
  "./pages/job/detail/page.tsx": {
    id: "pages/job/detail/page";
    page: "/job/detail/:id";
  };
  "./pages/company/profile/page.tsx": {
    id: "pages/company/profile/page";
    page: "/company/profile";
  };
  "./pages/company/cv/list/page.tsx": {
    id: "pages/company/cv/list/page";
    page: "/company/cv/list";
  };
  "./pages/company/cv/detail/page.tsx": {
    id: "pages/company/cv/detail/page";
    page: "/company/cv/detail/:id";
  };
  "./pages/company/job/list/page.tsx": {
    id: "pages/company/job/list/page";
    page: "/company/job/list";
  };
  "./pages/company/job/create/page.tsx": {
    id: "pages/company/job/create/page";
    page: "/company/job/create";
  };
  "./pages/company/list/page.tsx": {
    id: "pages/company/list/page";
    page: "/company/list";
  };
  "./pages/company/detail/page.tsx": {
    id: "pages/company/detail/page";
    page: "/company/detail/:id";
  };
  "./pages/catchall.tsx": {
    id: "pages/catchall";
    page: "/*";
  };
};