// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/search/:keyword": {
    params: {
      "keyword": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/search/:keyword" | "/*";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/SearchHome.tsx": {
    id: "pages/SearchHome";
    page: "/search";
  };
  "./pages/search/page.tsx": {
    id: "pages/search/page";
    page: "/search/:keyword";
  };
  "./pages/catchall.tsx": {
    id: "pages/catchall";
    page: "/*";
  };
};